#定期自动编译
name: WRT-SCHEDULE

#CI计划
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 21 * * *'

#CI任务
jobs:
  build_x86noPIE:
    uses: ./.github/workflows/WRT-CONTAINER.yml
    with:
      WRT_REPO: 'immortalwrt/immortalwrt'
      WRT_BRANCH: 'openwrt-24.10'
      WRT_CONF: 'x86_noPIE'
  
  build_x86:
    uses: ./.github/workflows/WRT-CONTAINER.yml
    with:
      WRT_REPO: 'immortalwrt/immortalwrt'
      WRT_BRANCH: 'openwrt-24.10'
      WRT_CONF: 'x86_sr'

  build_erx:
    uses: ./.github/workflows/WRT-CONTAINER.yml
    with:
      WRT_REPO: 'immortalwrt/immortalwrt'
      WRT_BRANCH: 'openwrt-24.10'
      WRT_CONF: 'mips_erx_noPIE'
